### ISSUE TITLE
Path to COLLADA2GLTF_BIN

### ISSUE THREAD

**Issue by KoalaGeo** [AuScope/geomodel-2-3dweb#1]
In configuration it states "Edit 'scripts/lib/exports/collada2gltf.py', change 'COLLADA2GLTF_BIN' to point to the path where 'COLLADA2GLTF-bin' resides"

Would that be on the line where I've added the comment below? 

``` python
''' Path where 'COLLADA2GLTF-bin' is located '''
if 'COLLADA2GLTF_BIN' in os.environ:
    COLLADA2GLTF_BIN = os.environ['COLLADA2GLTF_BIN']
elif 'HOME' in os.environ:
    COLLADA2GLTF_BIN = os.path.join(os.environ['HOME'], 'github', 'COLLADA2GLTF', 'build')
else:
    COLLADA2GLTF_BIN = "." #Enter Local Directory here? 
```

**Comment by KoalaGeo** [comment]
Notice it's looking for it as an environment variable first, so instead of adding a path, after compiling COLLADA2GLTF, I could add COLLADA2GLTF_BIN as an environment variable using the below?

```python
export PYTHONPATH= COLLADA2GLTF_BIN
```

**Comment by vjf** [comment]
Sorry for the confusion.

It's easiest to set COLLADA2GLTF_BIN from the shell prompt, e.g.
```
export COLLADA2GLTF_BIN=/home/koalageo/github/COLLADA2GLTF/build/
```
I have updated the README.md to make it clearer.
