### ISSUE TITLE
ASCII vs Binary versions of data

### ISSUE THREAD

**Issue by RichardScottOZ** [AuScope/geomodel-2-3dweb#3]
Hi,
​
I noticed on downloading this - some of the data dtypes are ascii and some are binary (hence not very useable if you don't have GOCAD).
​
The McArthur 3D model data - https://geoscience.nt.gov.au/gemis/ntgsjspui/handle/1/81751
​
Is it possible they can all be ASCII versions?  Can eventually write a binary converter I imagine, but certainly more time - e.g. the wells.  Or will the converter here solve that problem and you can take it from the formats here back into something else?
​
Thanks,
​
Richard

**Comment by vjf** [comment]
Hi Richard,

Thanks for the feedback.

Firstly, there are free viewer programs like "Geoscience Analyst" that can display many GOCAD object formats (https://mirageoscience.com/mining-industry-software/geoscience-analyst/) and include the ability to read those binary formats.

Secondly, you are right in that eventually I'd like the website to be capable of exporting to other formats. This isn't difficult, like you say, just a matter of time. For me the main problem with this is that most formats include little geological information. That is another discussion!

Vincent.

**Comment by RichardScottOZ** [comment]
Yes - although not SGRIDs for one.  That second part definitely is.

Also, geoh5py helping to gain access to some things there too - so possibly can go that way, too.

**Comment by RichardScottOZ** [comment]
Managed to use your code to extract.
